repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-added-large-files
        args: ['--maxkb=500']
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-r", "alos", "-s", "B101"]
        stages: [pre-push]

  - repo: local
    hooks:
      - id: mypy-check
        name: Type Check (mypy)
        entry: mypy alos
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]

      - id: pytest-check
        name: Unit Tests (pytest)
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
